name: Unit Test Only
on:
  pull_request:
    types:
      - opened
  workflow_dispatch:
jobs:
  unitTest:
    env:
      API_KEY: ${{ secrets.API_KEY }}
    runs-on: ubuntu-latest
    steps:
      - name: Get The Code
        uses: actions/checkout@v3
      - name: Get & Cache Deps
        uses: ./.github/actions/cached-deps


