#name: Matrix Demo
#on:
#  [ push,workflow_dispatch ]:
#jobs:
#  unitTest:
#    strategy:
#      matrix:
#        javaVersion: '17'
#        javaDist: 'temurin'
#
#    runs-on: ubuntu-latest
#    steps:
#      - name: Get The Code
#        uses: actions/checkout@v3
#      - name: Set up JDK 17
#        uses: actions/setup-java@v3
#        with:
#          java-version: ${{ matrix.javaVersion}}
#          distribution: ${{ matrix.javaDist}}
#      - name: Cache Gradle packages
#        uses: actions/cache@v3
#        with:
#          path: |
#            ~/.gradle/caches
#            ~/.gradle/wrapper
#          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
#          restore-keys: |
#            ${{ runner.os }}-gradle-
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
